export const ORDER_STATUSES = ["payment_confirmed", "order_review", "artwork_pending", "artwork_approved", "production_approved", "material_preparation", "printing", "stitching", "quality_check", "packing", "ready_to_dispatch", "dispatched", "delivered", "on_hold", "cancelled", "refund_pending", "refunded"] as const
export type OrderStatus = (typeof ORDER_STATUSES)[number]
export const ORDER_TRANSITIONS: Record<OrderStatus, readonly OrderStatus[]> = {
  payment_confirmed: ["order_review", "on_hold", "cancelled"], order_review: ["artwork_pending", "on_hold", "cancelled"], artwork_pending: ["on_hold", "cancelled"], artwork_approved: ["production_approved", "on_hold", "cancelled"], production_approved: ["material_preparation", "on_hold", "cancelled"], material_preparation: ["printing", "on_hold", "cancelled"], printing: ["stitching", "on_hold", "cancelled"], stitching: ["quality_check", "on_hold", "cancelled"], quality_check: ["packing", "printing", "on_hold", "cancelled"], packing: ["ready_to_dispatch", "quality_check", "on_hold", "cancelled"], ready_to_dispatch: ["dispatched", "packing", "on_hold", "cancelled"], dispatched: ["delivered", "on_hold"], delivered: [], on_hold: [], cancelled: ["refund_pending"], refund_pending: ["refunded"], refunded: [],
}
export const PUBLIC_STATUS_BY_INTERNAL: Record<OrderStatus, string> = { payment_confirmed: "order_received", order_review: "order_received", artwork_pending: "artwork_under_review", artwork_approved: "approved_for_production", production_approved: "approved_for_production", material_preparation: "in_production", printing: "in_production", stitching: "in_production", quality_check: "quality_check_and_packing", packing: "quality_check_and_packing", ready_to_dispatch: "preparing_dispatch", dispatched: "shipped", delivered: "delivered", on_hold: "action_required", cancelled: "cancelled", refund_pending: "cancelled", refunded: "cancelled" }
export const STAFF_ROLES = ["founder", "operations"] as const
export type StaffRole = (typeof STAFF_ROLES)[number]
export const STAFF_PERMISSIONS = { founder: ["view_all_orders", "change_order_status", "review_artwork", "manage_staff", "manage_discounts", "manage_refunds", "view_raw_payments"], operations: ["view_all_orders", "change_order_status", "review_artwork"] } as const
export function can(role: StaffRole, permission: string): boolean { return (STAFF_PERMISSIONS[role] as readonly string[]).includes(permission) }
